# Generated by Django 4.1.7 on 2023-04-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postpage_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='description',
        ),
    ]
